[project]
name = "llm-inference-techniques"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "xxhash>=3.6.0",
]

[dependency-groups]
dev = [
    "transformers>=4.57.5",
    "xxhash>=3.6.0",
]
